name = "chaincheck"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

# Productie-omgevingsvariabelen
# EXTERNAL_API_KEY zet je als secret: npx wrangler secret put EXTERNAL_API_KEY
[vars]
EXTERNAL_API_URL = "https://platform.marketingmadheads.com"

# Lokale ontwikkeling: zie .dev.vars
